#!/bin/sh

export DOTS_VERSION="2.3.20"
export GDK_BACKEND="wayland,x11,*"
export QT_QPA_PLATFORM="wayland;xcb"
export CLUTTER_BACKEND="wayland"

export XDG_CURRENT_DESKTOP="Hyprland"
export XDG_SESSION_DESKTOP="Hyprland"
export XDG_SESSION_TYPE="wayland"

export QT_AUTO_SCREEN_SCALE_FACTOR="1"
export QT_WAYLAND_DISABLE_WINDOWDECORATION="1"
export QT_QPA_PLATFORMTHEME="qt6ct"
export QT_QUICK_CONTROLS_STYLE="org.hyprland.style"

export GDK_SCALE="1"
export QT_SCALE_FACTOR="1"

export HYPRCURSOR_THEME="Bibata-Modern-Ice"
export HYPRCURSOR_SIZE="24"

export MOZ_ENABLE_WAYLAND="1"
export ELECTRON_OZONE_PLATFORM_HINT="auto"
export AQ_NO_ATOMIC="1"

export SSH_ASKPASS="/usr/bin/ksshaskpass"
export SSH_ASKPASS_REQUIRE="prefer"
export SSH_AUTH_SOCK="/tmp/ssh-agent-martinko.sock"

export __GLX_VENDOR_LIBRARY_NAME="nvidia"
export LIBVA_DRIVER_NAME="nvidia"

# Keep systemd user services and dbus activatable apps in sync with the imported env.
/usr/bin/dbus-update-activation-environment --systemd \
  DOTS_VERSION \
  GDK_BACKEND \
  QT_QPA_PLATFORM \
  CLUTTER_BACKEND \
  XDG_CURRENT_DESKTOP \
  XDG_SESSION_DESKTOP \
  XDG_SESSION_TYPE \
  QT_AUTO_SCREEN_SCALE_FACTOR \
  QT_WAYLAND_DISABLE_WINDOWDECORATION \
  QT_QPA_PLATFORMTHEME \
  QT_QUICK_CONTROLS_STYLE \
  GDK_SCALE \
  QT_SCALE_FACTOR \
  HYPRCURSOR_THEME \
  HYPRCURSOR_SIZE \
  MOZ_ENABLE_WAYLAND \
  ELECTRON_OZONE_PLATFORM_HINT \
  AQ_NO_ATOMIC \
  SSH_ASKPASS \
  SSH_ASKPASS_REQUIRE \
  SSH_AUTH_SOCK \
  __GLX_VENDOR_LIBRARY_NAME \
  LIBVA_DRIVER_NAME

/usr/bin/systemctl --user import-environment \
  DOTS_VERSION \
  GDK_BACKEND \
  QT_QPA_PLATFORM \
  CLUTTER_BACKEND \
  XDG_CURRENT_DESKTOP \
  XDG_SESSION_DESKTOP \
  XDG_SESSION_TYPE \
  QT_AUTO_SCREEN_SCALE_FACTOR \
  QT_WAYLAND_DISABLE_WINDOWDECORATION \
  QT_QPA_PLATFORMTHEME \
  QT_QUICK_CONTROLS_STYLE \
  GDK_SCALE \
  QT_SCALE_FACTOR \
  HYPRCURSOR_THEME \
  HYPRCURSOR_SIZE \
  MOZ_ENABLE_WAYLAND \
  ELECTRON_OZONE_PLATFORM_HINT \
  AQ_NO_ATOMIC \
  SSH_ASKPASS \
  SSH_ASKPASS_REQUIRE \
  SSH_AUTH_SOCK \
  __GLX_VENDOR_LIBRARY_NAME \
  LIBVA_DRIVER_NAME
