# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000307)
$foreground = rgb(EDF5F8)
$color0 = rgb(141C1F)
$color1 = rgb(457EAA)
$color2 = rgb(5C855B)
$color3 = rgb(4A81AB)
$color4 = rgb(95A53D)
$color5 = rgb(93A7B0)
$color6 = rgb(98AAB0)
$color7 = rgb(DDE8ED)
$color8 = rgb(9AA2A6)
$color9 = rgb(5CA8E3)
$color10 = rgb(7BB179)
$color11 = rgb(63ACE4)
$color12 = rgb(C7DC52)
$color13 = rgb(C4DEEB)
$color14 = rgb(CBE2EB)
$color15 = rgb(DDE8ED)
