$background = rgb(292220)
$foreground = rgb(F1E9DB)
$color0 = rgb(504845)
$color1 = rgb(3A1B12)
$color2 = rgb(6F4E2D)
$color3 = rgb(B8400A)
$color4 = rgb(9C8263)
$color5 = rgb(FD6905)
$color6 = rgb(D8C199)
$color7 = rgb(E3D8C4)
$color8 = rgb(9F9789)
$color9 = rgb(3A1B12)
$color10 = rgb(6F4E2D)
$color11 = rgb(B8400A)
$color12 = rgb(9C8263)
$color13 = rgb(FD6905)
$color14 = rgb(D8C199)
$color15 = rgb(E3D8C4)