# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

# Global for PacketTracer
# Fix drag and drop on XWayland
windowrule = no_initial_focus on, match:class PacketTracer
windowrule = float on, match:class PacketTracer
windowrule = no_anim on, match:class PacketTracer
windowrule = no_blur on, match:class PacketTracer
windowrule = no_dim on, match:class PacketTracer
windowrule = no_shadow on, match:class PacketTracer
windowrule = opaque on, match:class PacketTracer
windowrule = immediate on, match:class PacketTracer
windowrule = border_size 0, match:class PacketTracer
windowrule = rounding 0, match:class PacketTracer
windowrule = decorate 0, match:class PacketTracer
windowrule = nearest_neighbor on, match:class PacketTracer
windowrule = xray on, match:class PacketTracer
windowrule = min_size 1 1, match:class PacketTracer
windowrule = keep_aspect_ratio on, match:class PacketTracer, match:title Cisco Packet Tracer
windowrule = focus_on_activate on, match:class PacketTracer, match:title Cisco Packet Tracer
# windowrule = stayfocused, match:class PacketTracer, match:title Preference
#windowrule = min_size 486 628, match:class PacketTracer, match:title Preference
#windowrule = min_size 486 628, match:class PacketTracer, match:title .*outer.*
#windowrule = min_size 772 700, match:class PacketTracer, match:title .*witch.*
#windowrule = min_size 807 655, match:class PacketTracer, match:title .*PC.*
#windowrule = min_size 791 648, match:class PacketTracer, match:title .*Save File.


