# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Hypridle adapted for Niri 
# Original config submitted by https://github.com/SherLock707                                                       
                                                      
$iDIR="$HOME/.config/swaync/images/ja.png"

general {
    lock_cmd = pidof hyprlock || hyprlock 
    before_sleep_cmd = loginctl lock-session    
    after_sleep_cmd = niri msg action power-off-monitors
    ignore_dbus_inhibit = false             
}

# turn off screen faster if session is already locked
# (disabled by default)
# listener {
#     timeout = 30                            
#     on-timeout = pidof hyprlock && niri msg action power-off-monitors
# }

# Warn
listener {
    timeout = 240                     # 4 min
    on-timeout = notify-send -i $iDIR " You are idle!" 
    on-resume = notify-send -i $iDIR " Oh! you're Back" " Hello !!!"  
}

# Screenlock
listener {
    timeout = 300                     # 5 min
    on-timeout = loginctl lock-session 
}

# Turn off screen 
listener {
    timeout = 330                     # 5.5 min
    on-timeout = wlopm --off \*
    on-resume = wlopm --on \*
}

# Suspend PC (10 minutes)
# listener {
#     timeout = 600                     
#     on-timeout = systemctl suspend
# }
