# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EDF5F8
background         #000307
cursor             #B4D3B9

active_tab_foreground     #000307
active_tab_background     #EDF5F8
inactive_tab_foreground   #EDF5F8
inactive_tab_background   #000307

active_border_color   #EDF5F8
inactive_border_color #000307
bell_border_color     #457EAA

color0      #141C1F
color1		#457EAA
color2		#5C855B
color3		#4A81AB
color4		#95A53D
color5		#93A7B0
color6		#98AAB0
color7		#DDE8ED
color8		#9AA2A6
color9		#5CA8E3
color10		#7BB179
color11		#63ACE4
color12		#C7DC52
color13		#C4DEEB
color14		#CBE2EB
color15		#DDE8ED
