# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F9F9F9
background         #1B1B1B
cursor             #929292

active_tab_foreground     #1B1B1B
active_tab_background     #F9F9F9
inactive_tab_foreground   #F9F9F9
inactive_tab_background   #1B1B1B

active_border_color   #F9F9F9
inactive_border_color #1B1B1B
bell_border_color     #202020

color0      #424242
color1		#202020
color2		#212121
color3		#5A5A5A
color4		#5A5A5A
color5		#B2B3B2
color6		#B3B3B3
color7		#EEEEEE
color8		#A7A7A7
color9		#2B2B2B
color10		#2C2C2C
color11		#787878
color12		#787878
color13		#EEEEEE
color14		#EEEEEE
color15		#EEEEEE
